The main components that I selected were the 13S5P Hailong Battery Pack case and mount, the Bisida 30A BMS, the Monicel INR 18650 P26A cells, the Bafang 500W Motor Conversion kit, and a Shimano brake set. 

I chose this battery pack because the Hailong shape fit well within the dimensions of the main bike triangle. The Hailong shape is very common for DIY battery builders and it worked perfectly fine within the dimensions of my bike. It also had the correct mounting attachments to connect with the cylindrical downtube battery mount that I ordered. This specific type of pack had two holes on the bottom to thread bolts through that also threaded through the battery mount. It was very convenient to not have to braise my own holes. The hose clamps are able to fit nicely onto the cylindrical downtube.

I chose the Bisida 30A BMS because I knew that my controller had a max current of 18A and so 30A would not be bottlenecking my build in any way. There were some other BMS options with higher continuous current ratings but they were going to be too thick to fit into the limited internal pack space. So I went with the smaller option that was only about .5 cm thick. It was still a snug fit, and anything larger wouldn’t have worked.

I chose the Monicel INR 18650 P26A cells mainly because of their lifespan. They are rated to undergo around 500 successful cycles which is on the higher end of 18650 cells. I wanted the battery to last a long time because the steel frame was in great condition and I wanted to get the most out of this build that I could. For me the marginally more expensive cell was worth it if it meant I was getting good quality. There were slightly cheaper options I looked into but those were starting to dip in quality. I didn’t go with the more expensive 21700 cell because I knew that I didn’t really need the extra capacity for the 30 miles of range that I wanted. The pack voltage was already going to be a bit over sized for the motors required power and so having the extra capacity would have been a bit of overkill for the overall build.

I chose the Bafang 500W motor conversion kit for a couple of reasons. Firstly, I knew that this motor could definitely hit my 25mph top speed goal because of its KV rating of around 8.2 RPM/V and my nominal voltage of 46.8. This gave me about 380 RPM, which with the 26 inch wheel diameter, is about 29 MPH. This is free spin speed, actual speed is about 10-20 percent lower, which hovers around 25 MPH. I also knew that this geared hub motor was compatible with my 135mm read dropouts. Lastly, I had to take into consideration my rear dropout structural integrity. I was a bit cautious to go higher than 500W because while the dropouts are steel, they are very old and I didn’t want to push them too hard. That is why I installed a torque arm, so with that I should be fine. But I didn’t feel that there was any reason to go higher than 500W.

Lastly, I chose the Shimano brake set because I knew that they would be compatible with this bike's housing and rims. This is the same set that was on the bike before but it was a bit damaged and didn’t work very well so it needed to be replaced. The set was $30 for everything that you need to put on the bike and so I felt that it was well worth the money to replace the old brakes. 

